# Site wide configuration

title:  Rafael Sakurai
locale: pt_BR
url:    http://sakurai.dev.br
plugins:
  - jekyll-sitemap
  
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'


# Site owner
owner:
  name: Rafael Sakurai
  avatar: bio-photo.jpg
  bio: "Big Data Engineer at Tail and Editor at InfoQ Brazil."
  email:
  disqus-shortname: rafaelsakurai
  twitter: rafaelsakurai
  facebook: #username
  google:
    plus: RafaelSakurai
    analytics: UA-60110243-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rafaelsakurai
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: rafaelsakurai
  xing: #username
  instagram: #rafaelsakurai
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
